// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/compound.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7838640584206275548),
      name: 'Compound',
      lastPropertyId: const IdUid(5, 4715915376984089080),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5020215428769359637),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5592033166312746726),
            name: 'name',
            type: 9,
            flags: 2048,
            indexId: const IdUid(1, 561153013832620141)),
        ModelProperty(
            id: const IdUid(3, 2844648874399121217),
            name: 'modifier',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4685639201734783762),
            name: 'head',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4715915376984089080),
            name: 'frequencyClass',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7838640584206275548),
      lastIndexId: const IdUid(1, 561153013832620141),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Compound: EntityDefinition<Compound>(
        model: _entities[0],
        toOneRelations: (Compound object) => [],
        toManyRelations: (Compound object) => {},
        getId: (Compound object) => object.id,
        setId: (Compound object, int id) {
          object.id = id;
        },
        objectToFB: (Compound object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final modifierOffset = fbb.writeString(object.modifier);
          final headOffset = fbb.writeString(object.head);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, modifierOffset);
          fbb.addOffset(3, headOffset);
          fbb.addInt64(4, object.frequencyClass);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final modifierParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final headParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final frequencyClassParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = Compound(
              id: idParam,
              name: nameParam,
              modifier: modifierParam,
              head: headParam,
              frequencyClass: frequencyClassParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Compound] entity fields to define ObjectBox queries.
class Compound_ {
  /// see [Compound.id]
  static final id = QueryIntegerProperty<Compound>(_entities[0].properties[0]);

  /// see [Compound.name]
  static final name = QueryStringProperty<Compound>(_entities[0].properties[1]);

  /// see [Compound.modifier]
  static final modifier =
      QueryStringProperty<Compound>(_entities[0].properties[2]);

  /// see [Compound.head]
  static final head = QueryStringProperty<Compound>(_entities[0].properties[3]);

  /// see [Compound.frequencyClass]
  static final frequencyClass =
      QueryIntegerProperty<Compound>(_entities[0].properties[4]);
}
